"""initial

Revision ID: b04954bd8aec
Revises: 
Create Date: 2026-03-09 23:26:15.009429

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b04954bd8aec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency_code', sa.String(length=10), server_default='PLN', nullable=False),
    sa.Column('country_code', sa.String(length=5), server_default='PL', nullable=False),
    sa.Column('vat', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('parent_company_id', sa.UUID(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['parent_company_id'], ['base_companies.id'], name=op.f('fk_base_companies_parent_company_id_base_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_companies'))
    )
    op.create_index(op.f('ix_base_companies_company_id'), 'base_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_base_companies_tenant_id'), 'base_companies', ['tenant_id'], unique=False)
    op.create_table('base_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=5), server_default='PL', nullable=True),
    sa.Column('is_company', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('vat', sa.String(length=50), nullable=True),
    sa.Column('parent_partner_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_partner_id'], ['base_partners.id'], name=op.f('fk_base_partners_parent_partner_id_base_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_partners'))
    )
    op.create_index(op.f('ix_base_partners_company_id'), 'base_partners', ['company_id'], unique=False)
    op.create_index(op.f('ix_base_partners_tenant_id'), 'base_partners', ['tenant_id'], unique=False)
    op.create_table('base_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_base_tenants_slug'))
    )
    op.create_table('crm_pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency_code', sa.String(length=10), server_default='PLN', nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_pipelines'))
    )
    op.create_index(op.f('ix_crm_pipelines_company_id'), 'crm_pipelines', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_tenant_id'), 'crm_pipelines', ['tenant_id'], unique=False)
    op.create_table('ir_action_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), server_default='code', nullable=True),
    sa.Column('workflow_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_action_servers'))
    )
    op.create_table('ir_action_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('view_mode', sa.String(length=100), server_default='list,form', nullable=True),
    sa.Column('domain', sa.Text(), server_default='[]', nullable=True),
    sa.Column('context', sa.Text(), server_default='{}', nullable=True),
    sa.Column('target', sa.String(length=50), server_default='current', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_action_windows'))
    )
    op.create_table('ir_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('res_model', sa.String(length=255), nullable=True),
    sa.Column('res_id', sa.UUID(), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), server_default='0', nullable=True),
    sa.Column('store_fname', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_attachments'))
    )
    op.create_index(op.f('ix_ir_attachments_company_id'), 'ir_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_ir_attachments_res_id'), 'ir_attachments', ['res_id'], unique=False)
    op.create_index(op.f('ix_ir_attachments_res_model'), 'ir_attachments', ['res_model'], unique=False)
    op.create_index(op.f('ix_ir_attachments_tenant_id'), 'ir_attachments', ['tenant_id'], unique=False)
    op.create_table('ir_config_params',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('groups', sa.JSON(), server_default='[]', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_config_params')),
    sa.UniqueConstraint('key', name=op.f('uq_ir_config_params_key'))
    )
    op.create_table('ir_crons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('args', sa.Text(), server_default='[]', nullable=True),
    sa.Column('kwargs', sa.Text(), server_default='{}', nullable=True),
    sa.Column('interval_number', sa.Integer(), server_default='1', nullable=True),
    sa.Column('interval_type', sa.String(length=20), server_default='hours', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('next_call', sa.String(length=50), nullable=True),
    sa.Column('temporal_schedule_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_crons'))
    )
    op.create_table('ir_mail_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=100), nullable=True),
    sa.Column('auto_delete', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_mail_templates'))
    )
    op.create_table('ir_model_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('perm_read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('perm_write', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('perm_create', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('perm_unlink', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_model_access'))
    )
    op.create_index(op.f('ix_ir_model_access_model_name'), 'ir_model_access', ['model_name'], unique=False)
    op.create_index(op.f('ix_ir_model_access_role_name'), 'ir_model_access', ['role_name'], unique=False)
    op.create_table('ir_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_transient', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_models')),
    sa.UniqueConstraint('model_name', name=op.f('uq_ir_models_model_name'))
    )
    op.create_table('ir_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('domain_force', sa.Text(), server_default='[]', nullable=True),
    sa.Column('roles', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('is_global', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('perm_read', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('perm_write', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('perm_create', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('perm_unlink', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_rules'))
    )
    op.create_index(op.f('ix_ir_rules_model_name'), 'ir_rules', ['model_name'], unique=False)
    op.create_table('ir_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('suffix', sa.String(length=50), nullable=True),
    sa.Column('padding', sa.Integer(), server_default='5', nullable=True),
    sa.Column('number_next', sa.Integer(), server_default='1', nullable=True),
    sa.Column('number_increment', sa.Integer(), server_default='1', nullable=True),
    sa.Column('use_date_range', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_sequences')),
    sa.UniqueConstraint('code', name=op.f('uq_ir_sequences_code'))
    )
    op.create_table('ir_ui_menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), server_default='10', nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('groups', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('web_icon', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ir_ui_menus.id'], name=op.f('fk_ir_ui_menus_parent_id_ir_ui_menus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_ui_menus'))
    )
    op.create_table('base_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('company_ids', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('role_ids', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('last_login', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='pl', nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Warsaw', nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['base_partners.id'], name=op.f('fk_base_users_partner_id_base_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_users')),
    sa.UniqueConstraint('email', name=op.f('uq_base_users_email'))
    )
    op.create_index(op.f('ix_base_users_company_id'), 'base_users', ['company_id'], unique=False)
    op.create_index(op.f('ix_base_users_tenant_id'), 'base_users', ['tenant_id'], unique=False)
    op.create_table('crm_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='10', nullable=True),
    sa.Column('probability', sa.Float(), server_default='0', nullable=True),
    sa.Column('is_won', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_lost', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('fold', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], name=op.f('fk_crm_stages_pipeline_id_crm_pipelines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_stages'))
    )
    op.create_index(op.f('ix_crm_stages_company_id'), 'crm_stages', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_stages_tenant_id'), 'crm_stages', ['tenant_id'], unique=False)
    op.create_table('ir_model_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('readonly', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('selection_values', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('related_model', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ir_models.id'], name=op.f('fk_ir_model_fields_model_id_ir_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_model_fields'))
    )
    op.create_index(op.f('ix_ir_model_fields_model_name'), 'ir_model_fields', ['model_name'], unique=False)
    op.create_table('crm_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=5), server_default='PL', nullable=True),
    sa.Column('is_company', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('vat', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='lead', nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['base_users.id'], name=op.f('fk_crm_customers_assigned_user_id_base_users')),
    sa.ForeignKeyConstraint(['partner_id'], ['base_partners.id'], name=op.f('fk_crm_customers_partner_id_base_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_customers'))
    )
    op.create_index(op.f('ix_crm_customers_company_id'), 'crm_customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_customers_status'), 'crm_customers', ['status'], unique=False)
    op.create_index(op.f('ix_crm_customers_tenant_id'), 'crm_customers', ['tenant_id'], unique=False)
    op.create_table('crm_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('expected_revenue', sa.Float(), server_default='0', nullable=True),
    sa.Column('probability', sa.Float(), server_default='0', nullable=True),
    sa.Column('close_date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('workflow_run_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['base_users.id'], name=op.f('fk_crm_opportunities_assigned_user_id_base_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], name=op.f('fk_crm_opportunities_customer_id_crm_customers')),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], name=op.f('fk_crm_opportunities_pipeline_id_crm_pipelines')),
    sa.ForeignKeyConstraint(['stage_id'], ['crm_stages.id'], name=op.f('fk_crm_opportunities_stage_id_crm_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_opportunities'))
    )
    op.create_index(op.f('ix_crm_opportunities_company_id'), 'crm_opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_opportunities_tenant_id'), 'crm_opportunities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_opportunities_tenant_id'), table_name='crm_opportunities')
    op.drop_index(op.f('ix_crm_opportunities_company_id'), table_name='crm_opportunities')
    op.drop_table('crm_opportunities')
    op.drop_index(op.f('ix_crm_customers_tenant_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_status'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_company_id'), table_name='crm_customers')
    op.drop_table('crm_customers')
    op.drop_index(op.f('ix_ir_model_fields_model_name'), table_name='ir_model_fields')
    op.drop_table('ir_model_fields')
    op.drop_index(op.f('ix_crm_stages_tenant_id'), table_name='crm_stages')
    op.drop_index(op.f('ix_crm_stages_company_id'), table_name='crm_stages')
    op.drop_table('crm_stages')
    op.drop_index(op.f('ix_base_users_tenant_id'), table_name='base_users')
    op.drop_index(op.f('ix_base_users_company_id'), table_name='base_users')
    op.drop_table('base_users')
    op.drop_table('ir_ui_menus')
    op.drop_table('ir_sequences')
    op.drop_index(op.f('ix_ir_rules_model_name'), table_name='ir_rules')
    op.drop_table('ir_rules')
    op.drop_table('ir_models')
    op.drop_index(op.f('ix_ir_model_access_role_name'), table_name='ir_model_access')
    op.drop_index(op.f('ix_ir_model_access_model_name'), table_name='ir_model_access')
    op.drop_table('ir_model_access')
    op.drop_table('ir_mail_templates')
    op.drop_table('ir_crons')
    op.drop_table('ir_config_params')
    op.drop_index(op.f('ix_ir_attachments_tenant_id'), table_name='ir_attachments')
    op.drop_index(op.f('ix_ir_attachments_res_model'), table_name='ir_attachments')
    op.drop_index(op.f('ix_ir_attachments_res_id'), table_name='ir_attachments')
    op.drop_index(op.f('ix_ir_attachments_company_id'), table_name='ir_attachments')
    op.drop_table('ir_attachments')
    op.drop_table('ir_action_windows')
    op.drop_table('ir_action_servers')
    op.drop_index(op.f('ix_crm_pipelines_tenant_id'), table_name='crm_pipelines')
    op.drop_index(op.f('ix_crm_pipelines_company_id'), table_name='crm_pipelines')
    op.drop_table('crm_pipelines')
    op.drop_table('base_tenants')
    op.drop_index(op.f('ix_base_partners_tenant_id'), table_name='base_partners')
    op.drop_index(op.f('ix_base_partners_company_id'), table_name='base_partners')
    op.drop_table('base_partners')
    op.drop_index(op.f('ix_base_companies_tenant_id'), table_name='base_companies')
    op.drop_index(op.f('ix_base_companies_company_id'), table_name='base_companies')
    op.drop_table('base_companies')
    # ### end Alembic commands ###
